name: Apply

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      delay:
        type: string
        required: false
        default: ""
        description: "When? In"
      duration:
        type: string
        required: false
        default: 1 day
        description: "For how long?"
      environment:
        type: string
        required: false
        default: ""

jobs:
  apply:
    uses: stormreply/storm-library-for-terraform/.github/workflows/apply.yaml@main
    with:
      delay: ${{ inputs.delay }}
      duration: ${{ inputs.duration }}
    secrets: inherit
