name: Destroy

permissions:
  contents: read
  id-token: write

on:

  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      delay:
        type: string
        required: false
        default: ""
      environment:
        type: string
        required: false
        default: ""

jobs:
  destroy:
    uses: stormreply/storm-library-for-terraform/.github/workflows/destroy.yaml@main
    secrets: inherit
    with:
      delay: ${{ inputs.delay }}
      environment: ${{ inputs.environment }}
